language: node_js
node_js:
  - 5.1
cache:
  directories:
    - node_modules
before_script:
  - npm run build
after_success:
  - npm run deploy
notifications:
  slack:
    on_success: change
    on_failure: change
  email: false
